apiVersion: v1
kind: Service
metadata:
  name: linode-prod-lke-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
      component: web
